### ISSUE TITLE
一言分类更新

### ISSUE THREAD

**Issue by soulxyz** [GamerNoTitle/Hitokoto-Spider#1]
句子类型（参数）
参数	说明
a	动画
b	漫画
c	游戏
d	文学
e	原创
f	来自网络
g	其他
h	影视
i	诗词
j	网易云
k	哲学
l	抖机灵
其他	作为 动画 类型处理

**Comment by soulxyz** [comment]
来自https://developer.hitokoto.cn/sentence/#%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0

**Comment by GamerNoTitle** [comment]
已经更新最新一言最新分类类别，其中“抖机灵”类别被命名为Intelligent
