### ISSUE TITLE
新功能的提出以及开发进程

### ISSUE THREAD

**Issue by GamerNoTitle** [GamerNoTitle/Hitokoto-Spider#3]
如果你有新的想法，想让本程序实现新的功能，可以在此处提出\^V\^

**Comment by GamerNoTitle** [comment]
把原来在上面的内容搬下来了

---
每次抓取结果可能会抓到重复的数据，这个选项可以让你决定是否存入重复数据，重复数据可以用于计算重复率等数据；打印抓取结果选项可以让你实时看到抓取到的内容是什么；同时添加重复率显示、重复抓取次数显示
- [x] 打印抓取结果选项
- [x] 重复率显示
- [x] 重复抓取次数显示
- [x] 重复条目存入选项

**Comment by soulxyz** [comment]
新功能建议
①存入Excel表格功能
②追加写入
③追加写入时检测已有表格的数据并去重

**Comment by GamerNoTitle** [comment]
- [ ] Excel表格格式存储功能
- [x] 在原有的表格上追加写入
- [x] 在追加写入的前提下去重

**Comment by soulxyz** [comment]
新功能建议：
自动获取**status.hitokoto.cn**的一言数量

**Comment by GamerNoTitle** [comment]
> 新功能建议：
> 自动获取**status.hitokoto.cn**的一言数量

![](https://valinecdn.bili33.top/bilibiliHotKey/26.jpg)

**Comment by GamerNoTitle** [comment]
> 新功能建议：
> 自动获取**status.hitokoto.cn**的一言数量

已加
